@echo off
echo Compiling uwc3x.sma ...
IF EXIST compiled\uwc3x.amxx DEL compiled\uwc3x.amxx
amxxpc.exe uwc3x.sma -d1 -ocompiled/uwc3x.amxx
echo Compiling uwc3x.sma (debug)...
IF EXIST compiled\uwc3x_debug.amxx DEL compiled\uwc3x_debug.amxx
amxxpc.exe uwc3x.sma -d3 -ocompiled/uwc3x_debug.amxx
echo Coying files ...
IF EXIST compiled/uwc3x.amxx COPY /Y compiled\uwc3x.amxx ..\plugins\
IF EXIST compiled/uwc3x_debug.amxx COPY /Y compiled\uwc3x_debug.amxx ..\plugins\
echo Done ...
pause
